---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      provider: fabric8
      project: login-web
      version: 2.0.0-SNAPSHOT
      group: com.diegolirio
    name: login-web
  spec:
    ports:
    - nodePort: 30103
      port: 4200
      protocol: TCP
      targetPort: 4200
    selector:
      project: login-web
      provider: fabric8
      group: com.diegolirio
    type: NodePort
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      provider: fabric8
      project: login-web
      version: 2.0.0-SNAPSHOT
      group: com.diegolirio
    name: login-web
  spec:
    replicas: 1
    selector:
      matchLabels:
        project: login-web
        provider: fabric8
        version: 2.0.0-SNAPSHOT
        group: com.diegolirio
    template:
      metadata:
        labels:
          provider: fabric8
          project: login-web
          version: 2.0.0-SNAPSHOT
          group: com.diegolirio
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: registrydev.diegolirio.com.br:5000/login-web
          imagePullPolicy: Always
          name: login-web
          securityContext:
            privileged: false